name: nanosaber-mcmicro-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - numpy
  - pyfftw
  - itk
  - jupyterlab
  - tifffile
  - pandas
  - altair
  - altair_saver
  - scipy
  - anndata
  - snakemake>=6.0
  - seaborn
  - scikit-learn
  - openpyxl
  - beautifulsoup4
  - ipywidgets
  - pip
  - pip:
    - ashlar
    - wsireg
    - 'napari[all]'
    - flowcytometrytools